version: '3.1'
services :
  gprahql-elasticsearch:
    container_name: gprahql-elasticsearch
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - "./:/src"
    ports:
      - 3000:3000